name: ci

on:
  workflow_dispatch: 
  schedule:
    - cron: "0 */4 * * *"

jobs:
    CreateImage:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        strategy:
            matrix:
                node-version: [18]
        steps:
            - name: actions-timeline
              uses: Kesin11/actions-timeline@v1
              with:
               github-token: ${{ secrets.GITHUB_TOKEN }}

            - name: Checkout 🛎️
              uses: actions/checkout@v3
              with:
                  persist-credentials: false

            - name: Install PNPM
              uses: pnpm/action-setup@v2
              with:
                  version: ^7.0

            - name: Install Deps
              run: pnpm install --no-frozen-lockfile

            - name: Build
              run: pnpm run build

            - name: Create Image
              run: pnpm run start --cookie "${{ secrets.BING_COOKIE }}"

            - name: Push New Pic
              run: |
                  git config --local user.email "sxyx2008@163.com"
                  git config --local user.name "${{ github.actor }}"
                  git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
                  git add .
                  git commit -m "generated pic" || echo "no need to commit "
                  git pull origin main --rebase
                  git push -f || echo "no file change"
